version: "3"

services:
        ros:
                build: .
                tty: true
                network_mode: "host"
                privileged: true
                environment:
                        - DISPLAY=$DISPLAY
                volumes:
                        - /tmp/.X11-unix:/tmp/.X11-unix
                        - ./catkin_ws:/root/catkin_ws
